import fs from 'fs';
import path from 'path';

const source = path.join(process.cwd(), 'src/components/tools/product.html');
const dest = path.join(process.cwd(), 'src/pages/tools/business-plan-generator.astro');

let content = fs.readFileSync(source, 'utf-8');

// The Astro frontmatter to make it a valid route
const frontmatter = `---
// ZERO REBUILD STRATEGY: 100% BYTE-FOR-BYTE FIDELITY
// This file is generated programmatically from product.html.
// Do not edit this file directly.
---
`;

const premiumUI = `
<!-- ================= PREMIUM STUDIO INTERFACE ================= -->
<style>
/* Reset and Scope Toolbar Styles */
.premium-toolbar {
    position: fixed;
    bottom: 40px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    gap: 20px;
    background: rgba(255, 255, 255, 0.85);
    backdrop-filter: blur(16px);
    padding: 12px 24px;
    border-radius: 50px;
    box-shadow: 0 20px 60px rgba(0,0,0,0.15);
    z-index: 1000;
    border: 1px solid rgba(255,255,255,0.4);
    align-items: center;
    font-family: 'Inter', sans-serif;
}
.premium-toolbar a.back-btn {
    color: #7f8c8d;
    text-decoration: none;
    font-size: 14px;
    font-weight: 700;
    font-family: 'Montserrat', sans-serif;
    text-transform: uppercase;
    letter-spacing: 1px;
    transition: color 0.2s;
}
.premium-toolbar a.back-btn:hover { color: #008080; }
.premium-toolbar button.export-btn {
    background: #008080;
    color: white;
    border: none;
    padding: 10px 24px;
    border-radius: 30px;
    font-weight: 700;
    font-family: 'Montserrat', sans-serif;
    font-size: 14px;
    cursor: pointer;
    box-shadow: 0 4px 15px rgba(0,128,128,0.3);
    transition: all 0.2s;
}
.premium-toolbar button.export-btn:hover {
    transform: translateY(-2px);
    background: #006666;
    box-shadow: 0 6px 20px rgba(0,128,128,0.4);
}
.save-indicator {
    font-size: 11px;
    color: #7f8c8d;
    display: flex;
    align-items: center;
    gap: 6px;
    font-weight: 600;
    text-transform: uppercase;
}
.pulse-dot {
    width: 8px;
    height: 8px;
    background: #00bfa5;
    border-radius: 50%;
    animation: pulse 2s infinite;
}
@keyframes pulse {
    0% { box-shadow: 0 0 0 0 rgba(0,191,165, 0.4); }
    70% { box-shadow: 0 0 0 6px rgba(0,191,165, 0); }
    100% { box-shadow: 0 0 0 0 rgba(0,191,165, 0); }
}
@media print {
    .no-print { display: none !important; }
}
</style>

<div class="premium-toolbar no-print">
    <a href="/tools" class="back-btn">← Exit Studio</a>
    <div style="width: 1px; height: 24px; background: #d1d8e0;"></div>
    <div class="save-indicator"><div class="pulse-dot" id="pulse-dot"></div> <span id="save-text">Auto-Saving</span></div>
    <div style="width: 1px; height: 24px; background: #d1d8e0;"></div>
    <button class="export-btn" onclick="window.print()">Export to PDF</button>
</div>

<script>
    // ========= PERSISTENCE SCRIPT =========
    const STORAGE_KEY = "ccbp_business_plan_v3";
    const persistFields = document.querySelectorAll('input[type="text"], textarea, input[type="checkbox"]');
    
    function saveState() {
        const data = {};
        persistFields.forEach((field, index) => {
            data[index] = field.type === 'checkbox' ? field.checked : field.value;
        });
        localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
        
        // UI Pulse Feedback
        const dot = document.getElementById('pulse-dot');
        const text = document.getElementById('save-text');
        if (dot && text) {
            dot.style.background = '#00bfa5';
            dot.style.animation = 'none';
            text.innerText = 'All Changes Saved';
            setTimeout(() => {
                dot.style.background = '#008080';
                dot.style.animation = 'pulse 2s infinite';
                text.innerText = 'Auto-Saving';
            }, 1000);
        }
    }

    function loadState() {
        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved) {
            const data = JSON.parse(saved);
            persistFields.forEach((field, index) => {
                if (data[index] !== undefined) {
                    if (field.type === 'checkbox') field.checked = data[index];
                    else field.value = data[index];
                }
            });
            // Force sync trigger for loaded data
            const event = new Event('input', { bubbles: true });
            const syncNodes = document.querySelectorAll('.sync-co-name');
            if(syncNodes.length > 0) syncNodes[0].dispatchEvent(event);
        }
    }

    persistFields.forEach(field => {
        field.addEventListener('input', saveState);
        field.addEventListener('change', saveState);
    });

    // Initialize Auto-Load
    window.addEventListener('DOMContentLoaded', loadState);
</script>
`;

// Insert the frontmatter at top, and the UI right before closing body.
const finalContent = frontmatter + content.replace(/<\/body>/i, premiumUI + '\n</body>');

fs.writeFileSync(dest, finalContent);
console.log('Successfully generated business-plan-generator.astro with 100% byte-for-byte fidelity.');
